@ShopManager_HostAddress = http://localhost:5013/api/v1

GET {{ShopManager_HostAddress}}/shops
Accept: application/json

###

GET {{ShopManager_HostAddress}}/shops/all
Accept: application/json

###

### Create a new shop
POST {{ShopManager_HostAddress}}/shops/
Accept: application/json
Content-Type: application/json

{
  "ShopName": "Ushim's Baby Shop",
  "ShopAddress": "Ushim's Towers, Floor 3, 1st.",
  "ShopPhoneNumber": "12388767890",
  "ShopEmail": "rumic@ushimsbabyworld.com",
  "CacRegistrationNumber": "RC123996",
  "ShopDescription": "Ushim's Towers",
  "ShopLogo": "Ushim's Baby World Logo",
  "TaxIdentificationNumber": "TIN5564456",
  "TenantId": "01943280-357a-d13b-b8f4-4ec71c1a3fa0"
}

###

### Update a shop
PUT {{ShopManager_HostAddress}}/shops/019429ea-970b-057f-fbed-e11a747f8bc7
Accept: application/json
Content-Type: application/json

{
  "ShopId": "019429ea-970b-057f-fbed-e11a747f8bc7",
  "ShopName": "Ushim's Baby World",
  "ShopAddress": "Ushim's Towers, Floor 3, 1st.",
  "ShopPhoneNumber": "12388767890",
  "ShopEmailAddress": "rumic@ushimsbabyworld.com",
  "CacRegNumber": "RC121987",
  "ShopDescription": "Ushim's Baby World has the best baby products in the market.",
  "ShopLogo": "Ushim's Baby World Logo",
  "TaxId": "TIN55644270556",
  "TenantId": "019429dd-ddb6-3e20-a1f8-4add721e4d19"
}

###

### Update a shop
PUT {{ShopManager_HostAddress}}/shops/019332c0-3c6d-3467-4a6f-864ddadbad6c
Accept: application/json
Content-Type: application/json

{
  "ShopId": "019332c0-3c6d-3467-4a6f-864ddadbad6c",
  "ShopName": "Frank's Repair Shop",
  "ShopAddress": "No 56. RwangPam Street, Jos, Plateau State",
  "ShopPhoneNumber": "12388767890",
  "ShopEmailAddress": "shop2email.@franksrepairshop.xyz",
  "CacRegNumber": "RC123996",
  "ShopDescription": "We repairs all kinds of computers and sell computers also",
  "ShopLogo": "Shop 2 Logo",
  "TaxId": "TIN5564456",
  "TenantId": "019429dd-ddb6-3e20-a1f8-4add721e4d19"
}

###

### Delete a shop
DELETE {{ShopManager_HostAddress}}/shops/019332c0-3c6d-3467-4a6f-864ddadbad6c
Accept: application/json
Content-Type: application/json

{
    "ShopId": "019332c0-3c6d-3467-4a6f-864ddadbad6c"
}

###

### Create a Category
POST {{ShopManager_HostAddress}}/shops/categories/
Accept: application/json
Content-Type: application/json

{
  "Name": "Onesies",
  "Description": "Pin down for babies",
  "ShopId": "01943284-0049-f7da-2725-1e3a60ba1ea4"
}

###

### Create a Category
POST {{ShopManager_HostAddress}}/shops/categories/
Accept: application/json
Content-Type: application/json

{
  "Name": "Toys",
  "Description": "Toys for babies",
  "ShopId": "01943284-0049-f7da-2725-1e3a60ba1ea4"
}

###

### Get Shop Categories
GET {{ShopManager_HostAddress}}/shops/categories
Accept: application/json

###

### Get Tenants
GET {{ShopManager_HostAddress}}/tenants
Accept: application/json

###

### Get next n Tenants cursored by createdAt Instant
GET {{ShopManager_HostAddress}}/tenants/all

### Create a new tenant
POST {{ShopManager_HostAddress}}/tenants/
Accept: application/json
Content-Type: application/json

{
  "Name": "Franklyn Maduka",
  "ContactName": "Franklyn Maduka",
  "EmailAddress": "franksplace@bizdevomatics.xyz",
  "PhoneNumber": "08034567890",
  "Address": "Rwang Pam street, Jos, Plateau State",
  "BillingAddress": "Rwang Pam street, Jos, Plateau State",
  "ActivationStatus": 0,
  "NextBillingDate": "2024-12-21T23:06:57.174Z",
  "SubscriptionStartDate": "2024-09-21T23:06:57.174Z",
  "SubscriptionEndDate": "2024-11-19T23:06:57.174Z",
  "PaymentStatus": 1
}

###

### Create a new tenant
POST {{ShopManager_HostAddress}}/tenants/
Accept: application/json
Content-Type: application/json

{
  "Name": "Ruth Izang",
  "ContactName": "Ruth Izang",
  "EmailAddress": "rumic8080@gmail.com",
  "PhoneNumber": "08034567890",
  "Address": "Ushim's Baby World, Rwang Pam street, Jos, Plateau State",
  "BillingAddress": "Ushim's Baby World, Rwang Pam street, Jos, Plateau State",
  "ActivationStatus": 0,
  "NextBillingDate": "2025-02-01T23:06:57.174Z",
  "SubscriptionStartDate": "2025-01-03T01:38:50.185Z",
  "SubscriptionEndDate": "2025-02-04T01:38:50.185Z",
  "PaymentStatus": 1,
  "SubscriptionPlanTypeId": "01943278-a523-495c-75ae-493304b0f7a0"
}

###

### Get a tenant
GET {{ShopManager_HostAddress}}/tenants/0193517b-4392-0f51-e4cc-e3d6679c4951
Accept: application/json

###

### Delete a tenant
DELETE {{ShopManager_HostAddress}}/tenants/0193513a-e90c-7da9-f6ae-c26f99f1a5ad
Accept: application/json
Content-Type: application/json

{
    "TenantId": "0193513a-e90c-7da9-f6ae-c26f99f1a5ad"
}

###

### Get a tenant's SubscriptionPlans
GET {{ShopManager_HostAddress}}/tenants/0193517b-4392-0f51-e4cc-e3d6679c4951/subscriptionplans
Accept: application/json

###

### Get SubscriptionPlanTypes
GET {{ShopManager_HostAddress}}/subscriptionplantypes/all
Accept: application/json

###

### Create a new SubscriptionPlanType
POST {{ShopManager_HostAddress}}/subscriptionplantypes/
Accept: application/json
Content-Type: application/json

{
  "Name": "Basic",
  "Description": "Basic Subscription Plan",
  "Price": 5000,
  "Features": "Have one shop, basic inventory management, basic sales management",
  "Duration": 0
}

###

### Create a new SubscriptionPlanType
POST {{ShopManager_HostAddress}}/subscriptionplantypes/
Accept: application/json
Content-Type: application/json

{
  "Name": "Pro",
  "Description": "Pro Subscription Plan",
  "Price": 8000,
  "Features": "Have five shops, with everything from Basic Plan plus Invoicing, Reporting.",
  "Duration": 0
}

###